services:
  db:
    image: postgres:latest
    container_name: sadvm-db
    env_file:
      - .env
    ports:
      - "5432:5432" # Exposes PostgreSQL to the host, remove if not needed
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: 